<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password must be between 6 and 999 characters</name>
   <tag></tag>
   <elementGuidId>54cedcf9-3092-441c-8c71-0d1fe2c4b8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Password-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Password-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61466107-e592-4b65-ac53-de844f7efb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password-error</value>
      <webElementGuid>7983f7c7-087d-46cd-a185-f470db17bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>'Password' must be between 6 and 999 characters.</value>
      <webElementGuid>5fe88502-505f-4e1c-bc7c-abf742c3e7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password-error&quot;)</value>
      <webElementGuid>69f9113b-f1df-4b98-9a09-c9aaf4e568bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Password-error']</value>
      <webElementGuid>93484a1d-b685-4ac2-bcf0-7508c18b3d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/form/div/div[2]/div/fieldset[2]/div/div/span/span</value>
      <webElementGuid>24f9a8dd-2e01-41d0-ba08-70c584735883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[2]</value>
      <webElementGuid>167c0d6f-8297-4e62-b4b7-d248eea4c169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Password'])[1]/following::span[2]</value>
      <webElementGuid>f903d70b-a95e-4b27-8bc0-25bba151f8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm password'])[1]/preceding::span[1]</value>
      <webElementGuid>75d4e390-25f6-4915-8eb9-2df65722ecdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The password and confirmation password do not match.'])[1]/preceding::span[1]</value>
      <webElementGuid>e0b4a53e-0573-4720-a4e2-21b92b70adca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/span/span</value>
      <webElementGuid>9fc24218-ec4b-4489-9d8d-1a6f11a6bcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Password-error' and (text() = concat(&quot;'&quot; , &quot;Password&quot; , &quot;'&quot; , &quot; must be between 6 and 999 characters.&quot;) or . = concat(&quot;'&quot; , &quot;Password&quot; , &quot;'&quot; , &quot; must be between 6 and 999 characters.&quot;))]</value>
      <webElementGuid>95a086b9-d246-4ac8-87cd-41d02bf9d686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
