<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register</name>
   <tag></tag>
   <elementGuidId>cbf69112-d482-401e-9605-27aadf4b0121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='register-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;register-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3295af2-0a50-4750-a71b-4e395eafc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aab975d4-71ad-4b25-a6d8-4d77104a7402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>05b58179-cf04-4162-96e8-2ca2c46b1dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>register-button</value>
      <webElementGuid>ccafaf61-5e1c-4c92-b1ea-94eaa7933366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							Register
						</value>
      <webElementGuid>bab2dbeb-3c85-47ac-a342-dbb1aeeae63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;page registration-page&quot;]/div[@class=&quot;page-body row&quot;]/div[@class=&quot;col-12 col-lg-9 col-xl-8&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col&quot;]/button[@class=&quot;btn btn-primary btn-lg&quot;]</value>
      <webElementGuid>27dad952-9ad3-4abd-a99b-c94ba821c7db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='register-button']</value>
      <webElementGuid>07c5cf8d-e4d0-41e9-8e8f-3dffceaeaa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/form/div/div[2]/div/div[2]/div/button</value>
      <webElementGuid>dfc49677-359f-4fab-85a7-974d698d79cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Input elements with asterisk are required and have to be filled out.'])[1]/following::button[1]</value>
      <webElementGuid>b58515a2-7e77-45d1-94e7-9ea591d32d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/following::button[1]</value>
      <webElementGuid>33711c21-f7f4-4374-a24e-cd35f6e6204a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations'])[1]/preceding::button[1]</value>
      <webElementGuid>e96da3de-153f-4c85-94ac-0c02798672d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Brands'])[2]/preceding::button[1]</value>
      <webElementGuid>cd8f39db-009e-4d29-b05e-67b0a8cc4357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>b4f92e09-4523-44b6-84de-7ad18e020b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'register-button' and (text() = '
							Register
						' or . = '
							Register
						')]</value>
      <webElementGuid>81d74801-c29f-43a7-b1aa-18471807b2e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
