<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Options_Newsletter</name>
   <tag></tag>
   <elementGuidId>017be1ba-adbe-4815-89b3-bc7e7b6f3ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Newsletter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Newsletter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3fc1c6-5be0-444e-9cbd-ad24f06e3b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-box form-check-input</value>
      <webElementGuid>7666bee0-6ec0-4c92-b55a-3cfb6cee4629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9aa94ac5-8716-4750-af51-0bbcfabdb7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>'Newsletter' must not be empty.</value>
      <webElementGuid>2fa47f4d-3daa-4a23-aae5-c73fe64bb7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Newsletter</value>
      <webElementGuid>435656b0-6bb1-4830-9ce5-cc40398ba5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Newsletter</value>
      <webElementGuid>8e48581b-e27c-4382-8c1d-15ff436998b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dad9903e-6ade-4f1f-86bf-58646e244f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3dd8ff3-e261-4774-b884-378cb9cf04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Newsletter&quot;)</value>
      <webElementGuid>b5ae7383-1c30-46a5-ab3b-c2627e8ead5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Newsletter']</value>
      <webElementGuid>1cf9a751-03ab-4226-8f60-f67a1b48a245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/form/div/div[2]/div/fieldset[4]/div/div/div/input</value>
      <webElementGuid>afeb810c-ae96-4767-8ced-2f6319f80bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div/input</value>
      <webElementGuid>222eec3a-cef3-4231-b66d-86bafef8370d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Newsletter' and @name = 'Newsletter' and @type = 'checkbox']</value>
      <webElementGuid>cb2f0215-5a51-4fe4-b147-21359bf3fc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
