<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company name_Company</name>
   <tag></tag>
   <elementGuidId>b3b7c601-cda4-4899-85f3-452ffbecc24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7868170d-88e8-4663-bf16-59419418dbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1e91130d-9380-4263-a085-df877e033334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>a4dfc79c-29bf-48e5-8a18-76b123c3ae0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>7e601c4c-a3c2-41a9-b826-31c7bc61527e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Optional</value>
      <webElementGuid>b311b3aa-05c7-4110-87c3-a3e456a1de66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0f575b9-eac5-40c9-95e0-96cb77e1ae0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Company&quot;)</value>
      <webElementGuid>3a6dc3ce-7716-4bcf-8b9f-08da58af8f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Company']</value>
      <webElementGuid>998bf102-10d2-49be-b5b8-600805ad2a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/form/div/div[2]/div/fieldset[3]/div/div/input</value>
      <webElementGuid>1f57a17b-34d6-4a1a-8b7d-3f6578c77de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/input</value>
      <webElementGuid>5bf8a665-6113-498c-a53c-8463c29172eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Company' and @name = 'Company' and @placeholder = 'Optional' and @type = 'text']</value>
      <webElementGuid>231ab540-db2e-4b75-b394-6565388ea62a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
