<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>60b6eee2-651f-41bd-8c7a-9e0dd024d494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-center']/div/div[2]/div[2]/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.btn-lg.btn-block.register-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>574019f4-6aeb-4d37-ba58-57c2d672fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-lg btn-block register-button</value>
      <webElementGuid>9d9422d6-d6ed-434d-a9eb-3bdb7d69cf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/samples/TestComplete12/smartstore/register?returnUrl=%2fsamples%2fTestComplete12%2fsmartstore%2f</value>
      <webElementGuid>2e313136-fc7f-4639-b5b3-88d4ed2df0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Register
							</value>
      <webElementGuid>8fa942dd-0412-4abf-a6c8-4f6f4db9b1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-center&quot;)/div[@class=&quot;page login-page&quot;]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-12 col-md-5 col-lg-6 col-xl-7 order-md-first&quot;]/div[@class=&quot;register-block&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-auto&quot;]/a[@class=&quot;btn btn-warning btn-lg btn-block register-button&quot;]</value>
      <webElementGuid>0448dd7e-56ac-40f6-a1bd-f0a1b9e40c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-center']/div/div[2]/div[2]/div[2]/div/div/a</value>
      <webElementGuid>17575c6a-25ff-49e7-9d06-fee10e2f990b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>8b429252-f5a9-4cfc-bcbf-698df7593795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not registered yet?'])[1]/following::a[1]</value>
      <webElementGuid>b1d2d271-45a3-4f2b-909b-333f07375821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/following::a[1]</value>
      <webElementGuid>d60a68cb-a06d-4930-a613-155c2ae0578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informations'])[1]/preceding::a[5]</value>
      <webElementGuid>cfc5ace3-10d4-4b40-a823-379d8ecfa7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Brands'])[2]/preceding::a[5]</value>
      <webElementGuid>6fd389f9-ba62-4ab5-b4ee-3e07d5705db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>04435122-a089-44c3-97ad-8ee05c4ff4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/samples/TestComplete12/smartstore/register?returnUrl=%2fsamples%2fTestComplete12%2fsmartstore%2f')]</value>
      <webElementGuid>8ae7f710-5cc0-4d00-8e3b-fd35d3a8f16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/a</value>
      <webElementGuid>5d4706fa-d95f-47fb-ae64-107b7da4ab5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/samples/TestComplete12/smartstore/register?returnUrl=%2fsamples%2fTestComplete12%2fsmartstore%2f' and (text() = '
								Register
							' or . = '
								Register
							')]</value>
      <webElementGuid>ccbc77c4-9333-4172-b1a4-82889a98e1a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
